spring.application.name=User Service

# -------------------DB1 ---------------------
spring.datasource.user-db.jdbc-url=jdbc:mysql://localhost:3306/user_service_db
spring.datasource.user-db.username=root
spring.datasource.user-db.password=Root@123
spring.datasource.user-db.driver-class-name=com.mysql.cj.jdbc.Driver

# -------------------DB2 ---------------------
spring.datasource.chef-db.jdbc-url=jdbc:mysql://localhost:3306/chef_service_db
spring.datasource.chef-db.username=root
spring.datasource.chef-db.password=Root@123
spring.datasource.chef-db.driver-class-name=com.mysql.cj.jdbc.Driver

# ------------------ JPA --------------------
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true